
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: example.com
    Template:
      Count: 1
PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true    
    Template:
      Count: 3 #Change this number if you want to introduce more peers
    Users:
      Count: 1