
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: frogfrogjump.com
    Template:
      Count: 1
PeerOrgs:
  - Name: Org1
    Domain: org1.frogfrogjump.com
    EnableNodeOUs: true    
    Template:
      Count: 3
    Users:
      Count: 1